name = "VectorizedKmers"
uuid = "2ef45bd6-4c2b-43d8-88b3-40597287359a"
authors = ["Anton Oresten <anton.oresten42@gmail.com>"]
version = "0.9.0"

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"

[weakdeps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"

[extensions]
BioSequencesExt = "BioSequences"

[compat]
BioSequences = "3"
julia = "1"

[extras]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BioSequences"]
